### PR TITLE
commonjs support

### PR DESCRIPTION
**Pull request by ctaepper**
I added commonjs support **the angular way** (as opposed to #166)

### CODE REVIEW

**Comment by dsnoeck** [comment]
@rubenv Can we have that one merge ? Is there anything blocking ? 
I saw that #166 is open since 18 months. Is this project still active or you are looking for maintainer ?

**Comment by rubenv** [comment]
@dsnoeck It's still active but I want to stabilize and freeze the project. We have some pretty big users of this project and I'm very wary of breaking things. So for the most part there won't be much new features.

Bugs is another matter and if anyone wants to help out, I'll gladly welcome it.

**Comment by rubenv** [comment]
Released as `v2.3.8`.

**Comment by dsnoeck** [comment]
@rubenv, ok and thanks a lot for merging #166

**Pull request merged**
