### PR TITLE
Add Textdomain Support

### PR DESCRIPTION
**Pull request by KevinMartin**
Using either syntax:
```
<span translate="testDomain">Hello</span>
<span translate translate-domain="testDomain">Hello</span>
```

Works with Contexts/Interpolation and Plurals
Tests are included

### CODE REVIEW

**Comment by ThomasHambach** [comment]
What is the status on this implementation? I am for one definitely looking for such functionality.

**Comment by netstyler** [comment]
Would be a great feature! Why is it still not merged? ;)

**Comment by tagoh** [comment]
I'm surprised this feature isn't yet implemented. it is required to support the internationalization on projects which uses multiple modules like AngularJS as this project is also supposed to work on, right?

**Comment by rubenv** [comment]
The full reasoning why this won't go in is here: https://github.com/rubenv/angular-gettext/pull/115#issuecomment-63677736

I'm closing this issue. Anyone who can demonstrate a common real-life problem that is currently impossible with angular-gettext: feel free to open a new issue. Fact is that a good project setup removes the need for domains: proper project structure has large benefits outside i18n alone.

**Pull request closed without merging**
