### PR TITLE
Fix duplicate translation and improve performance

### LINKED ISSUE #179: directive 'translate' broken in angular 1.4.0-rc0. No element.parent()
Probably because of $animate breaking changes in angular 1.4.0-rc0

```javascript
<span translate>translation_key_will_break</span>

<span>{{'translation_key_works'|translate}}</span>
```

Angular Error: element.parent is not a function

angular-gettext.js line 197,198: 
https://github.com/rubenv/angular-gettext/blob/master/dist/angular-gettext.js#L197
```javascript
                        $animate.enter(newContents, element);
                        $animate.leave(oldContents);
```

### PR DESCRIPTION
**Pull request by circlingthesun**
When angular-gettext starts, it replaces all translated strings. This is redundant if the language is unchanged. It also seems to be the cause of issues with ngAnimate. This PR resolves issues experienced when applying https://github.com/angular/angular.js/pull/11722 in order to fix #179. It may also be a fix for #161.

### CODE REVIEW

**Comment by rubenv** [comment]
@circlingthesun interesting! I'll need to give this some testing, but it looks sensible to me.

**Comment by rubenv** [comment]
According to https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent, `textContent` is only available in IE9.

At [Ticketmatic](http://www.ticketmatic.com/) we still have support for IE8 on the sales pages (using Angular 1.2), so we'll need to find a fallback for this. I don't want to burden you with supporting IE8, so I'll have a look at what's possible myself.

**Comment by rubenv** [comment]
Wait no, this isn't a problem at all:

```
if (translated === oldContents[0].textContent){
```

This will never be true on IE8 (`textContent` is undefined), so it'll always fall back to the slow path (but work).

Which is perfect for me, I'd rather not ship workarounds for that dinosaur, I don't really care if performance is a bit less (well, it's exactly the same as it always was).

Let's give it a bit more testing to see if it doesn't cause extra problems, but as far as I can see, this is a great improvement.

**Comment by rubenv** [comment]
Ran into a crasher which we didn't have before:

screen shot 2015-04-30 at 10 28 01

As you can see, the `th` does not have contents.

The offending HTML:
```html
<th translate="translate"></th>
```

Which is obviously incorrect, but that doesn't mean we should crash on it :-)

**Comment by circlingthesun** [comment]
Actually there is oldContents.html() as @crisbeto pointed out which is what gettext-tools is using: https://github.com/rubenv/angular-gettext-tools/blob/master/lib/extract.js#L291. So thats probably what I should have used.

**Comment by rubenv** [comment]
Mind you, that `.html()` is in cheerio, not jQuery or anything.

**Comment by circlingthesun** [comment]
As far as I understand cheerio emulates jQuery and Angular has the .html() function in jqLite (https://docs.angularjs.org/api/ng/function/angular.element). I've updated the PR accordingly.

**Comment by circlingthesun** [comment]
So that breaks ...

**Comment by circlingthesun** [comment]
It broke because I accidentally committed nonsense I was trying out after my last commit. I've rebased it and added a test for the empty string scenario you raised.

**Comment by rubenv** [comment]
I haven't found anything that breaks with the latest version. Unless anyone else encounters problems: I'll be merging this soon.

**Comment by rubenv** [comment]
Released as `v2.1.0`. Thanks a lot @circlingthesun!

**Pull request merged**
