### PR TITLE
add object with translations to directive attribute

### PR DESCRIPTION
**Pull request by mbrammer**
Add translation params to a directive.
`<span translate="{username: 'Dexter'}">Hello {{username}}!</span>`

### CODE REVIEW

**Comment by mbrammer** [comment]
forgot to compile and fixed update. new PR in progress

**Comment by gabegorelick** [comment]
FYI you can just force push to a PR instead of opening a new one.

**Comment by rubenv** [comment]
I've refrained from the value of the translate attribute until now because I see two potential problems:

1. What will this do with regards to performance?
2. What shall we do with [Jade](http://jade-lang.com/), which has the bad habit of compiling this markup:

```jade
div(translate) test
```

To this:

```html
<div translate="translate">test</div>
```

**Comment by mbrammer** [comment]
I had a little bit time to fix these issues.
Regarding your points.
1) There shouldn't be any big performance issue, because the `update()` is just triggered when something changed inside the scope of the directive.
2) I fixed this by testing if the attribute is an object or not. `translateValues` is undefined in case of `<div translate="translate">test</div>`

**Comment by rubenv** [comment]
> 1) There shouldn't be any big performance issue, because the update() is just triggered when something changed inside the scope of the directive.

Well, you do have the two `eval` calls, which for a Jade user would happen for every string. I'm not familiar with how `eval` is implemented in Angular.JS (should look it up), but I doubt it'll be a lightweight operation :-)

**Pull request closed without merging**
