### PR TITLE
Adds support for providing translation context params. 

### PR DESCRIPTION
**Pull request by IShotTheSheriff**
It enables to separate translation messages from custom logic ex. filters. Detailed description in Issue #285.
In addition it also extracts common utility functions - trim and assert from translate directive into a service. Service holds additional utility methods needed for translation-params mechanism to work. Thanks to that no 3rd party dependencies was required and codebase is still ES5.

### CODE REVIEW

**Comment by rubenv** [comment]
While I don't really want to add new features, I have to admit that this makes total sense.

Code looks great too.

Just one question, take for instance this case:

```js
     it("Should translate with multiple translate params along with normal scope interpolation", function () {
         $rootScope.item = "Headphones";
         $rootScope.cost = 5;
         $rootScope.currency = "$";
         catalog.setCurrentLanguage("pl");
         var el = $compile("<div><h1 translate translate-params-product=\"item | uppercase\">This product: {{product}} costs {{cost}}{{currency}}.</h1></div>")($rootScope);
         $rootScope.$digest();
         assert.equal(el.text(), "Ten produkt: HEADPHONES kosztuje 5$.");
     });
```

Will changes to `item` be reflected in the final string?

**Comment by IShotTheSheriff** [comment]
It definitely will. Whole mechanism bases on $interpolation with provided context so whenever `item` changes the final string updates as well.

**Comment by rubenv** [comment]
Merged! Travis was failing, but I've tested it locally and things do work.

Excellent, excellent work, thanks a lot. Only remaining things is updating the website with a section on how these work. A new section under advanced is probably the right place: https://angular-gettext.rocketeer.be/dev-guide/

Code for the website is here if you feel like writing this: https://github.com/rubenv/angular-gettext-website If not, I'll file an issue to make sure we get round to this in the future.

As you may have noticed, I am not always the fastest maintainer (not for a lack of wanting, but things get in the way). If it's OK with you, I'll add you as a committer to the project, feel free to push fixes directly, should anything pop up (just ping me for a release). Sounds good?

**Comment by IShotTheSheriff** [comment]
Thanks a lot!

Lack of time is fully understandable and you're doing great job by maintaining couple of open source projects despite it. I will be more than happy to write documentation for website. Also being a committer will be a great honour so it sounds great for me!

**Comment by rubenv** [comment]
Cool, welcome on board :-)

**Pull request merged**
