### PR TITLE
Fix IE9 reordering HTML attributes in the key.

### PR DESCRIPTION
**Pull request by maxpeterson**
It seems that ie9 reorders some attributes this causes the key not to match.

For example `<span title="The title" class="test">Test</span>` will be rendered as `<span class="test" title="The title">Test</span>` by ie9. The result is that the key does not match the value when looked up by the directive.

The fix very similar to #131

### CODE REVIEW

**Comment by maxpeterson** [comment]
@rubenv should I have created a test for this? Do you have any way of automating IE tests.

**Comment by rubenv** [comment]
I would love to have automated IE tests, but we sadly don't have them yet.

Any help there would be greatly appreciated.

For now I test all changes through our main project that heavily uses angular-gettext. For that one we have a full CI setup (with tons of browsers). Unfortunately I can't use it for open-source purposes (who would pay the bills? :-)).

**Comment by rubenv** [comment]
As for this patch, I'll test it, if it works it's good to go in.

**Comment by rubenv** [comment]
Merged! Thanks a lot!

**Comment by rubenv** [comment]
Tagged as "v2.0.2"

**Comment by maxpeterson** [comment]
Thanks

**Pull request merged**
