### PR TITLE
Provide scope on every update

### PR DESCRIPTION
**Pull request by cakeinpanic**
I've noticed that using directive `translate-params-` we lose all parameters on language change.
I've fixed it

### CODE REVIEW

**Comment by rubenv** [comment]
Cool, thanks! Would you mind adding a test for this? Just to make sure we don't break it again in the future.

**Comment by cakeinpanic** [comment]
Voila!

**Comment by rubenv** [comment]
@cakeinpanic When I add this test, without applying the other changes, it also passes.

So either this test checks something else, or the patch isn't really needed :-)

**Comment by cakeinpanic** [comment]
@rubenv i've edited test(it was incorrect first time)
now it's failing on old version

**Comment by rubenv** [comment]
Merged, thanks!

**Comment by rubenv** [comment]
Released as `v2.3.6`.

**Pull request merged**
