### PR TITLE
Added jsdoc/ngdoc

### PR DESCRIPTION
**Pull request by wingedfox**
Added comprehensive inline jsdoc/ngdoc for both IDE completion and online docs generation.
Demo of live doc http://wingedfox.github.io/dgeni-alive/docs/angular-gettext

### CODE REVIEW

**Comment by rubenv** [comment]
This is great!

**Comment by rubenv** [comment]
Merged, thanks!

**Comment by rubenv** [comment]
Released to NPM as `v2.2.1`. Thanks a lot!

**Comment by wingedfox** [comment]
You're welcome!
If you don't mind, I'll add improvements and guides there as well.

**Comment by rubenv** [comment]
I'd love to have a way to compile these API docs into the website, ideally in the same look/feel.

To keep all the docs in once place, otherwise that'll just lead to confusion.

If you're interested, the website source is over here: https://github.com/rubenv/angular-gettext-website

**Comment by wingedfox** [comment]
Got it.
There are 2 options:
1. build complete code.angularjs.org-like docs
2. integrate generated docs to the wintersmith

For the second one, you need to work out the design details as long as current template has no place to put the components navigation pane, at least.

**Pull request merged**
