### PR TITLE
fix: get correct plural when n is in string

### LINKED ISSUE #305: Singular only shows well the first time
`<span translate translate-n="activity.length" translate-plural="{{$count}} hours">1 hour</span>`

I haves this, activity.length intitila value is 1, and "1 hour" is show.  When activity.length increases, "{{$count}} hours" is shown, but ehen returns to 1, "1 **hours** is shown"

### PR DESCRIPTION
**Pull request by zhuangya**
ref #313 fix #305

### CODE REVIEW

**Comment by zhuangya** [comment]
🤔  anyone?

**Comment by duall** [comment]
+1

**Comment by rubenv** [comment]
As mentioned in #275, I'd rather not merge this. Make sure your data is good before it arrives at angular-gettext.

JS might not be strongly-typed, but that doesn't mean that types don't matter. Strings aren't numbers, the only person who knows if a conversion can be done safely is you.

**Comment by zhuangya** [comment]
> Make sure your data is good before it arrives at angular-gettext.

so you're telling me, every single time i use angular-gettext with input(type=range), i need something like [this](https://gist.github.com/zhuangya/38476c504d29d39d8d2bfae5e11b5060#file-angular-gettext-issue-305-workaround-html-L26)?

**Pull request closed without merging**
